# scripts/scaffold/source_freshness_scaffold.py
"""Generate source freshness YAML configuration."""
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

# Column name patterns that indicate a loaded_at timestamp.
LOADED_AT_PATTERNS = [
    "_loaded_at",
    "_updated_at",
    "_modified_at",
    "_created_at",
    "updated_date",
    "modified_date",
    "last_modified",
    "load_timestamp",
    "updated_at",
    "created_at",
    "modified_at",
]

# Table name keywords for classification.
TRANSACTIONAL_KEYWORDS = (
    "transaction",
    "event",
    "log",
    "order",
    "payment",
    "sale",
    "booking",
)
REFERENCE_KEYWORDS = (
    "type",
    "code",
    "categor",
    "mapping",
    "lookup",
    "status_code",
)


def classify_table_type(table_name: str) -> str:
    """Classify a table as transactional, reference, or standard."""
    name_lower = table_name.lower()
    if any(kw in name_lower for kw in TRANSACTIONAL_KEYWORDS):
        return "transactional"
    if any(kw in name_lower for kw in REFERENCE_KEYWORDS):
        return "reference"
    return "standard"


def suggest_loaded_at_field(columns: list[str]) -> str | None:
    """Find the best candidate loaded_at_field from column names."""
    for pattern in LOADED_AT_PATTERNS:
        for col in columns:
            if col.lower().endswith(pattern) or col.lower() == pattern:
                return col
    return None


def generate_freshness_block(
    table_name: str,
    loaded_at_field: str,
    table_type: str = "standard",
) -> str:
    """Generate a YAML freshness block for one table."""
    thresholds = {
        "transactional": ("12", "hour", "24", "hour"),
        "reference": ("7", "day", "14", "day"),
        "standard": ("24", "hour", "48", "hour"),
    }
    warn_count, warn_period, error_count, error_period = thresholds.get(
        table_type, thresholds["standard"]
    )

    comment = ""
    if table_type == "reference":
        comment = "  # reference table — infrequent updates"
    elif table_type == "transactional":
        comment = "  # transactional — tighter threshold"

    return (
        f"      - name: {table_name}\n"
        f"        loaded_at_field: {loaded_at_field}\n"
        f"        freshness:\n"
        f"          warn_after: {{count: {warn_count}, period: {warn_period}}}{comment}\n"
        f"          error_after: {{count: {error_count}, period: {error_period}}}\n"
        f"          # Adjust based on this source's actual sync cadence"
    )


def run_freshness_scaffold(selector: str, apply_changes: bool = False) -> int:
    """Generate freshness YAML for a source.

    In dry-run mode (default): prints YAML to stdout.
    In --apply mode: finds the source YAML file and inserts the freshness blocks.
    """
    from scripts._core.selector import resolve_selector, load_manifest

    targets = resolve_selector(selector)
    manifest = load_manifest()
    generated_blocks: list[tuple[str, str]] = []  # (table_name, block)

    for target in targets:
        for _key, node in manifest.get("sources", {}).items():
            if node.get("name") == target.table:
                columns = list(node.get("columns", {}).keys())
                loaded_at = suggest_loaded_at_field(columns)

                if loaded_at is None:
                    logger.warning(
                        "%s: no candidate loaded_at_field found", target.table
                    )
                    continue

                table_type = classify_table_type(target.table)
                block = generate_freshness_block(target.table, loaded_at, table_type)
                generated_blocks.append((target.table, block))

    if not apply_changes:
        print("# Suggested freshness configuration")
        print("# Generated by scaffold — review thresholds before committing\n")
        for _, block in generated_blocks:
            print(block)
            print()
        return 0

    # --apply mode: find and update source YAML files
    import re
    from pathlib import Path

    models_dir = Path("models")
    for table_name, block in generated_blocks:
        # Find the source YAML file containing this table
        yaml_files = list(models_dir.rglob("*.yml")) + list(
            models_dir.rglob("*.yaml")
        )
        for yaml_path in yaml_files:
            content = yaml_path.read_text(encoding="utf-8")
            if f"name: {table_name}" in content:
                # Inject freshness block after "name: <table_name>"
                pattern = rf"(      - name: {re.escape(table_name)}\n)"
                replacement = (
                    r"\1"
                    + "\n".join(
                        f"        {line}" if line.strip() else line
                        for line in block.strip().split("\n")[
                            1:
                        ]  # skip "- name: X" (already in file)
                    )
                    + "\n"
                )
                updated = re.sub(pattern, replacement, content, count=1)
                if updated != content:
                    yaml_path.write_text(updated, encoding="utf-8")
                    print(f"  Updated: {yaml_path}")
                    break
        else:
            print(f"  Warning: No source YAML found for {table_name} — output to stdout:")
            print(block)

    return 0
